language: smalltalk
sudo: false

# Select operating system(s)
os:
  - linux
  - osx

smalltalk:
  - Pharo-6.1
  - Pharo-7.0
  - Pharo32-8.0
  - Pharo64-8.0

addons:
  homebrew:
    packages:
      - sqlite3
  apt:
    packages:
      - sqlite3
